"""Type stubs for the compiled ``dedupe_rs._native`` extension module."""

from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple, Union

Record = Dict[str, Any]
RecordID = Union[int, str]
RecordPair = Tuple[Record, Record]
TrainingData = Dict[str, List[RecordPair]]
Cluster = Tuple[Tuple[RecordID, ...], Tuple[float, ...]]
ScoredPair = Tuple[Tuple[RecordID, RecordID], float]
LookupResults = Dict[RecordID, Tuple[Tuple[RecordID, float], ...]]

def version() -> str: ...
def canonicalize(record_cluster: Sequence[Record]) -> Record: ...
def write_training(labeled_pairs: TrainingData, file_obj: Any) -> None: ...
def read_training(file_obj: Any) -> TrainingData: ...
def training_data_link(
    data_1: Dict[RecordID, Record],
    data_2: Dict[RecordID, Record],
    common_key: str,
    training_size: int = ...,
) -> TrainingData: ...
def training_data_dedupe(
    data: Dict[RecordID, Record],
    common_key: str,
    training_size: int = ...,
) -> TrainingData: ...
def settings_to_dict(settings_file: Any) -> Any: ...

class Dedupe:
    def __init__(
        self,
        variable_definition: Sequence[Any],
        num_cores: Optional[int] = ...,
        in_memory: bool = ...,
        seed: int = ...,
    ) -> None: ...
    def prepare_training(
        self,
        data: Dict[RecordID, Record],
        training_file: Optional[Any] = ...,
        sample_size: int = ...,
        blocked_proportion: float = ...,
    ) -> None: ...
    def uncertain_pairs(self) -> List[Record]: ...
    def mark_pairs(self, labeled_pairs: TrainingData) -> None: ...
    def train(self, recall: float = ..., index_predicates: bool = ...) -> None: ...
    def partition(
        self, data: Dict[RecordID, Record], threshold: float = ...
    ) -> List[Cluster]: ...
    def pairs(self, data: Dict[RecordID, Record]) -> List[Tuple[Tuple[RecordID, Record], Tuple[RecordID, Record]]]: ...
    def score(self, pairs: Any) -> List[ScoredPair]: ...
    def one_to_one(self, scores: Any, threshold: float = ...) -> List[ScoredPair]: ...
    def many_to_one(self, scores: Any, threshold: float = ...) -> List[ScoredPair]: ...
    def cluster(self, scores: Any, threshold: float = ...) -> List[Cluster]: ...
    def write_training(self, file_obj: Any) -> None: ...
    def read_training(self, file_obj: Any) -> None: ...
    def write_settings(self, file_obj: Any) -> None: ...
    @property
    def training_pairs(self) -> TrainingData: ...
    @property
    def predicates(self) -> List[str]: ...
    @property
    def data_model_len(self) -> int: ...
    @property
    def field_names(self) -> List[str]: ...

class RecordLink:
    def __init__(
        self,
        variable_definition: Sequence[Any],
        num_cores: Optional[int] = ...,
        in_memory: bool = ...,
        seed: int = ...,
    ) -> None: ...
    def prepare_training(
        self,
        data_1: Dict[RecordID, Record],
        data_2: Dict[RecordID, Record],
        training_file: Optional[Any] = ...,
        sample_size: int = ...,
        blocked_proportion: float = ...,
    ) -> None: ...
    def uncertain_pairs(self) -> List[Record]: ...
    def mark_pairs(self, labeled_pairs: TrainingData) -> None: ...
    def train(self, recall: float = ..., index_predicates: bool = ...) -> None: ...
    def join(
        self,
        data_1: Dict[RecordID, Record],
        data_2: Dict[RecordID, Record],
        threshold: float = ...,
        constraint: str = ...,
    ) -> List[ScoredPair]: ...
    def pairs(
        self, data_1: Dict[RecordID, Record], data_2: Dict[RecordID, Record]
    ) -> List[Tuple[Tuple[RecordID, Record], Tuple[RecordID, Record]]]: ...
    def score(self, pairs: Any) -> List[ScoredPair]: ...
    def write_training(self, file_obj: Any) -> None: ...
    def write_settings(self, file_obj: Any) -> None: ...
    @property
    def training_pairs(self) -> TrainingData: ...
    @property
    def predicates(self) -> List[str]: ...
    @property
    def field_names(self) -> List[str]: ...

class Gazetteer:
    def __init__(
        self,
        variable_definition: Sequence[Any],
        num_cores: Optional[int] = ...,
        in_memory: bool = ...,
        seed: int = ...,
    ) -> None: ...
    def prepare_training(
        self,
        data_1: Dict[RecordID, Record],
        data_2: Dict[RecordID, Record],
        training_file: Optional[Any] = ...,
        sample_size: int = ...,
        blocked_proportion: float = ...,
    ) -> None: ...
    def uncertain_pairs(self) -> List[Record]: ...
    def mark_pairs(self, labeled_pairs: TrainingData) -> None: ...
    def train(self, recall: float = ..., index_predicates: bool = ...) -> None: ...
    def index(self, data: Dict[RecordID, Record]) -> None: ...
    def unindex(self, data: Dict[RecordID, Record]) -> None: ...
    def search(
        self,
        data: Dict[RecordID, Record],
        threshold: float = ...,
        n_matches: int = ...,
    ) -> LookupResults: ...
    @property
    def indexed_len(self) -> int: ...
    @property
    def field_names(self) -> List[str]: ...

class StaticDedupe:
    @staticmethod
    def from_settings(
        settings_file: Any, num_cores: Optional[int] = ..., in_memory: bool = ...
    ) -> "StaticDedupe": ...
    def partition(
        self, data: Dict[RecordID, Record], threshold: float = ...
    ) -> List[Cluster]: ...
    def pairs(self, data: Dict[RecordID, Record]) -> List[Any]: ...
    def score(self, pairs: Any) -> List[ScoredPair]: ...

class StaticRecordLink:
    @staticmethod
    def from_settings(
        settings_file: Any, num_cores: Optional[int] = ..., in_memory: bool = ...
    ) -> "StaticRecordLink": ...
    def join(
        self,
        data_1: Dict[RecordID, Record],
        data_2: Dict[RecordID, Record],
        threshold: float = ...,
        constraint: str = ...,
    ) -> List[ScoredPair]: ...

class StaticGazetteer:
    @staticmethod
    def from_settings(
        settings_file: Any, num_cores: Optional[int] = ..., in_memory: bool = ...
    ) -> "StaticGazetteer": ...
    def index(self, data: Dict[RecordID, Record]) -> None: ...
    def unindex(self, data: Dict[RecordID, Record]) -> None: ...
    def search(
        self,
        data: Dict[RecordID, Record],
        threshold: float = ...,
        n_matches: int = ...,
    ) -> LookupResults: ...
